name: Deploy image from tag

on:
  push:
    tags:
      - "**"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    uses: ./.github/workflows/deploy-image.yml
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    with:
      image-tags: ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:${{ github.ref_name }}